<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Wilaya;

class WilayaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $wilayas =     [
            [
                // 'id' => 1,
                'name' => 'Adrar',
                'ar_name' => 'أدرار',
                'code' => 1,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 2,
                'name' => 'Chlef',
                'ar_name' => 'الشلف',
                'code' => 2,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 3,
                'name' => 'Laghouat',
                'ar_name' => 'الأغواط',
                'code' => 3,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 4,
                'name' => 'Oum El Bouaghi',
                'ar_name' => 'أم البواقي',
                'code' => 4,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 5,
                'name' => 'Batna',
                'ar_name' => 'باتنة',
                'code' => 5,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 6,
                'name' => 'Béjaïa',
                'ar_name' => 'بجاية',
                'code' => 6,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 7,
                'name' => 'Biskra',
                'ar_name' => 'بسكرة',
                'code' => 7,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 8,
                'name' => 'Béchar',
                'ar_name' => 'بشار',
                'code' => 8,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 9,
                'name' => 'Blida',
                'ar_name' => 'البليدة',
                'code' => 9,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 10,
                'name' => 'Bouïra',
                'ar_name' => 'البويرة',
                'code' => 10,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 11,
                'name' => 'Tamanrasset',
                'ar_name' => 'تمنراست',
                'code' => 11,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 12,
                'name' => 'Tébessa',
                'ar_name' => 'تبسة',
                'code' => 12,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 13,
                'name' => 'Tlemcen',
                'ar_name' => 'تلمسان',
                'code' => 13,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 14,
                'name' => 'Tiaret',
                'ar_name' => 'تيارت',
                'code' => 14,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 15,
                'name' => 'Tizi Ouzou',
                'ar_name' => 'تيزي وزو',
                'code' => 15,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 16,
                'name' => 'Alger',
                'ar_name' => 'الجزائر',
                'code' => 16,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 17,
                'name' => 'Djelfa',
                'ar_name' => 'الجلفة',
                'code' => 17,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 18,
                'name' => 'Jijel',
                'ar_name' => 'جيجل',
                'code' => 18,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 19,
                'name' => 'Sétif',
                'ar_name' => 'سطيف',
                'code' => 19,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 20,
                'name' => 'Saïda',
                'ar_name' => 'سعيدة',
                'code' => 20,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 21,
                'name' => 'Skikda',
                'ar_name' => 'سكيكدة',
                'code' => 21,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 22,
                'name' => 'Sidi Bel Abbès',
                'ar_name' => 'سيدي بلعباس',
                'code' => 22,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 23,
                'name' => 'Annaba',
                'ar_name' => 'عنابة',
                'code' => 23,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 24,
                'name' => 'Guelma',
                'ar_name' => 'قالمة',
                'code' => 24,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 25,
                'name' => 'Constantine',
                'ar_name' => 'قسنطينة',
                'code' => 25,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 26,
                'name' => 'Médéa',
                'ar_name' => 'المدية',
                'code' => 26,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 27,
                'name' => 'Mostaganem',
                'ar_name' => 'مستغانم',
                'code' => 27,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 28,
                'name' => 'M\'Sila',
                'ar_name' => 'المسيلة',
                'code' => 28,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 29,
                'name' => 'Mascara',
                'ar_name' => 'معسكر',
                'code' => 29,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 30,
                'name' => 'Ouargla',
                'ar_name' => 'ورقلة',
                'code' => 30,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 31,
                'name' => 'Oran',
                'ar_name' => 'وهران',
                'code' => 31,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 32,
                'name' => 'El Bayadh',
                'ar_name' => 'البيض',
                'code' => 32,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 33,
                'name' => 'Illizi',
                'ar_name' => 'اليزي',
                'code' => 33,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 34,
                'name' => 'Bordj Bou Arréridj',
                'ar_name' => 'برج بوعريريج',
                'code' => 34,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 35,
                'name' => 'Boumerdès',
                'ar_name' => 'بومرداس',
                'code' => 35,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 36,
                'name' => 'El Tarf',
                'ar_name' => 'الطارف',
                'code' => 36,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 37,
                'name' => 'Tindouf',
                'ar_name' => 'تندوف',
                'code' => 37,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 38,
                'name' => 'Tissemsilt',
                'ar_name' => 'تسمسيلت',
                'code' => 38,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 39,
                'name' => 'El Oued',
                'ar_name' => 'الوادي',
                'code' => 39,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 40,
                'name' => 'Khenchela',
                'ar_name' => 'خنشلة',
                'code' => 40,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 41,
                'name' => 'Souk Ahras',
                'ar_name' => 'سوق أهراس',
                'code' => 41,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 42,
                'name' => 'Tipaza',
                'ar_name' => 'تيبازة',
                'code' => 42,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 43,
                'name' => 'Mila',
                'ar_name' => 'ميلة',
                'code' => 43,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 44,
                'name' => 'Aïn Defla',
                'ar_name' => 'عين الدفلى',
                'code' => 44,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 45,
                'name' => 'Naâma',
                'ar_name' => 'النعامة',
                'code' => 45,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 46,
                'name' => 'Aïn Témouchent',
                'ar_name' => 'عين تموشنت',
                'code' => 46,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 47,
                'name' => 'Ghardaïa',
                'ar_name' => 'غرداية',
                'code' => 47,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                // 'id' => 48,
                'name' => 'Relizane',
                'ar_name' => 'غليزان',
                'code' => 48,
                // 'created_at' => date('Y-m-d H:i:s'),
                // 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Timimoun',
                'ar_name' => 'تيميمون',
                'code' => 49,
            ],
            [
                'name' => 'Bordj Baji Mokhtar',
                'ar_name' => 'برج باجي مختار',
                'code' => 50,
            ],
            [
                'name' => 'Ouled Djellal',
                'ar_name' => 'أولاد جلال',
                'code' => 51,
            ],
            [
                'name' => 'Béni Abbès',
                'ar_name' => 'بني عباس',
                'code' => 52,
            ],
            [
                'name' => 'In Salah',
                'ar_name' => 'عين صالح',
                'code' => 53,
            ],
            [
                'name' => 'In Guezzam',
                'ar_name' => 'عين قزّام',
                'code' => 54,
            ],
            [
                'name' => 'Touggourt',
                'ar_name' => 'تقرت',
                'code' => 55,
            ],
            [
                'name' => 'Djanet',
                'ar_name' => 'جانت',
                'code' => 56,
            ],
            [
                'name' => 'El M\'ghair',
                'ar_name' => 'المغير',
                'code' => 57,
            ],
            [
                'name' => 'El Menia',
                'ar_name' => 'المنيعة',
                'code' => 58,

            ]
        ];

        foreach ($wilayas as $wilaya) {
            Wilaya::create($wilaya);
        }
    }
}
